# Generated by Django 2.2.2 on 2019-06-23 12:26

from decimal import Decimal
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodIncidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('level', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=4)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Flood Areas',
            },
        ),
        migrations.CreateModel(
            name='FloodProneArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=1000)),
                ('avg_rainfall', models.DecimalField(blank=True, decimal_places=4, help_text='Average rainfall per month', max_digits=10, null=True)),
                ('msl', models.DecimalField(blank=True, decimal_places=4, help_text='Mean Sea Level', max_digits=10, null=True)),
                ('peak', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The highest point of this area', null=True, srid=4326)),
                ('folder', models.URLField(blank=True, help_text='File folder for this area', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('up_cells', models.BigIntegerField()),
                ('discharge', models.FloatField()),
                ('width', models.FloatField()),
                ('width5', models.FloatField()),
                ('width95', models.FloatField()),
                ('depth', models.FloatField()),
                ('depth5', models.FloatField()),
                ('depth95', models.FloatField()),
                ('arcid', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=2)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('un', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('pop2005', models.BigIntegerField()),
                ('region', models.IntegerField()),
                ('subregion', models.IntegerField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
